### ISSUE TITLE
Expose IJavaScriptExecutor.ExecuteAsyncScript

### ISSUE THREAD

**Issue by atifaziz** [StephenCleary/BrowserBoss#10]
Just like we have `Boss.Script` that calls into [`IJavaScriptExecutor.ExecuteScript`](https://seleniumhq.github.io/selenium/docs/api/dotnet/html/M_OpenQA_Selenium_IJavaScriptExecutor_ExecuteScript.htm), it seems natural to have a member that exposes [`IJavaScriptExecutor.ExecuteAsyncScript`](https://seleniumhq.github.io/selenium/docs/api/dotnet/html/M_OpenQA_Selenium_IJavaScriptExecutor_ExecuteAsyncScript.htm).

I need this for executing a script using XHR asynchronously in the browser. I can certainly go over `IWebDriver` but if you'd be happy to entertain this addition then I can submit a PR.

**Comment by StephenCleary** [comment]
Sure, that would be great!
