### ISSUE TITLE
Chrome Browser crashes with sample code from readme

### ISSUE THREAD

**Issue by mrchief** [StephenCleary/BrowserBoss#7]
![image](https://cloud.githubusercontent.com/assets/781818/18519950/cc29da0e-7a73-11e6-9510-325b992464b3.png)

![image](https://cloud.githubusercontent.com/assets/781818/18519969/e1149724-7a73-11e6-9a10-aff5ffc0f668.png)

Chrome Version 52.0.2743.116 m
Win 7 x64 SP1

**Comment by StephenCleary** [comment]
Sorry, I'm unable to repro this with Chrome 54.0.2840.99 m

Most likely it was a bugfix on their side.
